---
- hosts: all
  gather_facts: true
  tasks:
    - name: Run Podified EDPM deployment
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework"
        cmd: >-
          ansible-playbook deploy-edpm.yml
          -e @scenarios/centos-9/base.yml
          -e @scenarios/centos-9/edpm_ci.yml
          -e @scenarios/centos-9/zuul_inventory.yml
      register: edpm_deploy_status
