- name: Run pre_deploy hooks
  vars:
    hooks: "{{ pre_deploy | default([]) }}"
    step: pre_deploy
  ansible.builtin.import_playbook: ./hooks.yml

- hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Call predeploy
      ansible.builtin.include_role:
        name: edpm_prepare

    - name: Create and provision external computes
      ansible.builtin.include_role:
        name: libvirt_manager
        tasks_from: deploy_edpm_compute.yml

- name: Run post_deploy hooks
  vars:
    hooks: "{{ post_deploy | default([]) }}"
    step: post_deploy
  ansible.builtin.import_playbook: ./hooks.yml

- hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Deploy EDPM
      ansible.builtin.include_role:
        name: edpm_deploy
      when: deploy_edpm | default('false') | bool
