---
# Follow steps as described on:
# https://github.com/openstack-k8s-operators/install_yamls/pull/127
- name: Install nmstate operator
  environment:
    KUBECONFIG: "{{ cifmw_edpm_deploy_kubeconfig }}"
  ci_make:
    dry_run: "{{ cifmw_edpm_deploy_make_dryrun }}"
    output_dir: "{{ cifmw_edpm_deploy_basedir }}/artifacts"
    chdir: "{{ cifmw_edpm_deploy_installyamls }}"
    target: "nmstate"
    params:
      OUT: "{{ cifmw_edpm_deploy_basedir }}/artifacts"

- name: Configure CRC interface
  environment:
    KUBECONFIG: "{{ cifmw_edpm_deploy_kubeconfig }}"
  ci_make:
    dry_run: "{{ cifmw_edpm_deploy_make_dryrun }}"
    output_dir: "{{ cifmw_edpm_deploy_basedir }}/artifacts"
    chdir: "{{ cifmw_edpm_deploy_installyamls }}"
    target: "nncp"
    params:
      OUT: "{{ cifmw_edpm_deploy_basedir }}/artifacts"

- name: Create network-attachment-definitions for internalapi, storage and tenant
  environment:
    KUBECONFIG: "{{ cifmw_edpm_deploy_kubeconfig }}"
  ci_make:
    dry_run: "{{ cifmw_edpm_deploy_make_dryrun }}"
    output_dir: "{{ cifmw_edpm_deploy_basedir }}/artifacts"
    chdir: "{{ cifmw_edpm_deploy_installyamls }}"
    target: "netattach"
    params:
      OUT: "{{ cifmw_edpm_deploy_basedir }}/artifacts"

- name: Install metallb operator
  environment:
    KUBECONFIG: "{{ cifmw_edpm_deploy_kubeconfig }}"
  ci_make:
    dry_run: "{{ cifmw_edpm_deploy_make_dryrun }}"
    output_dir: "{{ cifmw_edpm_deploy_basedir }}/artifacts"
    chdir: "{{ cifmw_edpm_deploy_installyamls }}"
    target: "metallb"
    params:
      OUT: "{{ cifmw_edpm_deploy_basedir }}/artifacts"

- name: Create ipaddresspools and l2advertisement resources
  environment:
    KUBECONFIG: "{{ cifmw_edpm_deploy_kubeconfig }}"
  ci_make:
    dry_run: "{{ cifmw_edpm_deploy_make_dryrun }}"
    output_dir: "{{ cifmw_edpm_deploy_basedir }}/artifacts"
    chdir: "{{ cifmw_edpm_deploy_installyamls }}"
    target: "metallb_config"
    params:
      OUT: "{{ cifmw_edpm_deploy_basedir }}/artifacts"

- name: Create CRC storage
  environment:
    KUBECONFIG: "{{ cifmw_edpm_deploy_kubeconfig }}"
  ci_make:
    dry_run: "{{ cifmw_edpm_deploy_make_dryrun }}"
    output_dir: "{{ cifmw_edpm_deploy_basedir }}/artifacts"
    chdir: "{{ cifmw_edpm_deploy_installyamls }}"
    target: "crc_storage"
    params:
      OUT: "{{ cifmw_edpm_deploy_basedir }}/artifacts"

- name: Create input
  environment:
    KUBECONFIG: "{{ cifmw_edpm_deploy_kubeconfig }}"
  ci_make:
    dry_run: "{{ cifmw_edpm_deploy_make_dryrun }}"
    output_dir: "{{ cifmw_edpm_deploy_basedir }}/artifacts"
    chdir: "{{ cifmw_edpm_deploy_installyamls }}"
    target: "input"
    params:
      OUT: "{{ cifmw_edpm_deploy_basedir }}/artifacts"

- name: Install opentack-operator
  environment:
    KUBECONFIG: "{{ cifmw_edpm_deploy_kubeconfig }}"
  ci_make:
    dry_run: "{{ cifmw_edpm_deploy_make_dryrun }}"
    output_dir: "{{ cifmw_edpm_deploy_basedir }}/artifacts"
    chdir: "{{ cifmw_edpm_deploy_installyamls }}"
    target: "openstack"
    params:
      OUT: "{{ cifmw_edpm_deploy_basedir }}/artifacts"

- name: Deploy OpenStack
  environment:
    KUBECONFIG: "{{ cifmw_edpm_deploy_kubeconfig }}"
    OPENSTACK_CTLPLANE: config/samples/core_v1beta1_openstackcontrolplane_network_isolation.yaml
  ci_make:
    dry_run: "{{ cifmw_edpm_deploy_make_dryrun }}"
    output_dir: "{{ cifmw_edpm_deploy_basedir }}/artifacts"
    chdir: "{{ cifmw_edpm_deploy_installyamls }}"
    target: "openstack_deploy"
    params:
      OUT: "{{ cifmw_edpm_deploy_basedir }}/artifacts"
