---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Fetch namespaces to create
  ansible.builtin.set_fact:
    cifmw_openshift_setup_namespaces: >-
      {{
        ((
            ([cifmw_install_yamls_defaults['NAMESPACE']] +
              ([cifmw_install_yamls_defaults['OPERATOR_NAMESPACE']] if 'OPERATOR_NAMESPACE' is in cifmw_install_yamls_defaults else [])
            ) if cifmw_install_yamls_defaults is defined else []
        ) + cifmw_openshift_setup_create_namespaces) | unique
      }}

- name: Create required namespaces
  kubernetes.core.k8s:
    kubeconfig: "{{ cifmw_openshift_setup_kubeconfig | default(cifmw_kubeconfig) }}"
    name: "{{ item }}"
    kind: Namespace
    state: present
  with_items: "{{ cifmw_openshift_setup_namespaces }}"
  when: not cifmw_openshift_setup_dry_run

- name: Get internal OpenShift registry route
  kubernetes.core.k8s_info:
    kind: Route
    name: default-route
    namespace: openshift-image-registry
  register: cifmw_openshift_setup_registry_default_route

- name: Allow anonymous image-pulls in CRC registry for targeted namespaces
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ cifmw_openshift_setup_kubeconfig | default(cifmw_kubeconfig) }}"
    definition:
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: system:image-puller
        namespace: "{{ item }}"
      subjects:
      - kind: User
        name: system:anonymous
      - kind: User
        name: system:unauthenticated
      roleRef:
        kind: ClusterRole
        name: system:image-puller
  with_items: "{{ cifmw_openshift_setup_namespaces }}"
  when:
    - not cifmw_openshift_setup_dry_run
    - >
      (cifmw_openshift_setup_registry_default_route.resources | length > 0) and
      cifmw_openshift_setup_registry_default_route.resources[0].spec.host == cifmw_operator_build_push_registry
