---
- hosts: all
  gather_facts: true
  tasks:
    - name: Run EDPM build image
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework"
        cmd: >-
          ansible-playbook ci/playbooks/edpm_build_images/edpm_image_builder.yml
          -e @scenarios/centos-9/base.yml
          -e @scenarios/centos-9/edpm_build_images_ci.yml
          -e @scenarios/centos-9/zuul_inventory.yml
