---
- hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Perform CRC login
      ansible.builtin.include_role:
        name: rhol_crc
        tasks_from: add_crc_creds.yml

    - name: Disable the openshift-marketplace
      ansible.builtin.command: >-
        oc patch operatorhubs/cluster --type merge --patch '{"spec":{"sources":[{"disabled": true,"name": "redhat-marketplace"}]}}'
