---
- hosts: "{{ cifmw_target_hook_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Perform CRC login
      ansible.builtin.include_role:
        name: rhol_crc
        tasks_from: add_crc_creds.yml

    - name: Restart nova-scheduler to pick up cell1
      ansible.builtin.command: >-
        oc delete pod -n openstack -l service=nova-scheduler
